#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path


GENERATED_BY = "> Auto-generated by `python3 scripts/generate_bundle.py`. Do not edit manually."
OVH_BRAND_COLOR = "#0050D7"
SAFE_TOKENS = {
    "catalog",
    "capabilities",
    "get",
    "get-access",
    "get-console-url",
    "get-kind",
    "incident",
    "list",
    "list-capabilities",
    "list-compatible-os",
    "list-engines",
    "list-interventions",
    "list-kinds",
    "list-options",
    "list-periods",
    "list-plans",
    "list-secrets",
    "list-tasks",
    "list-versions",
    "messages",
    "service-info",
    "show",
    "statistics",
}
UNSAFE_TOKENS = {
    "abort",
    "activate-monthly-billing",
    "add",
    "associate-floating-ip",
    "attach",
    "bulk-delete",
    "change-contact",
    "change-contacts",
    "change-password",
    "confirm-termination",
    "copy",
    "create",
    "create-floating-ip",
    "delete",
    "detach",
    "disable",
    "edit",
    "enable",
    "exit-rescue",
    "purge",
    "reboot",
    "reboot-rescue",
    "refresh",
    "reinstall",
    "renew",
    "reply",
    "request-action",
    "request-boost",
    "reset",
    "reschedule",
    "restart",
    "restore",
    "resume",
    "set",
    "set-as-admin",
    "set-endpoint",
    "set-flavor",
    "set-load-balancers-subnet",
    "set-name",
    "set-password",
    "set-script",
    "shelve",
    "start",
    "stop",
    "switch",
    "terminate",
    "unblock-tcp-out",
    "unleash",
    "unshelve",
    "update",
    "upgrade",
}
TOP_LEVEL_ORDER = [
    "account",
    "alldom",
    "baremetal",
    "browser",
    "cdn-dedicated",
    "cloud",
    "config",
    "dedicated-ceph",
    "dedicated-cloud",
    "dedicated-cluster",
    "dedicated-nasha",
    "domain-name",
    "domain-zone",
    "email-domain",
    "email-mxplan",
    "email-pro",
    "hosting-private-database",
    "iam",
    "ip",
    "iploadbalancing",
    "ldp",
    "location",
    "login",
    "nutanix",
    "okms",
    "overthebox",
    "ovhcloudconnect",
    "pack-xdsl",
    "sms",
    "ssl",
    "ssl-gateway",
    "storage-netapp",
    "support-tickets",
    "telephony",
    "veeamcloudconnect",
    "veeamenterprise",
    "vmwareclouddirector-backup",
    "vmwareclouddirector-organization",
    "vps",
    "vrack",
    "vrackservices",
    "webhosting",
    "xdsl",
]
CLOUD_ORDER = [
    "project",
    "operation",
    "quota",
    "reference",
    "region",
    "user",
    "ssh-key",
    "instance",
    "kube",
    "loadbalancer",
    "network",
    "storage",
    "floating-ip",
    "ip-failover",
    "container-registry",
    "managed-database",
    "managed-analytics",
    "alerting",
    "rancher",
    "savings-plan",
]
EXCLUDED_TOP_LEVEL = {"cloud", "config", "login"}


@dataclass
class SkillSpec:
    key: str
    name: str
    title: str
    category: str
    cli_help: str
    description: str
    summary: str
    discovery_hint: str
    when_to_use: list[str]
    reference_slug: str
    doc_prefix: str | None = None
    prerequisites: list[str] = field(default_factory=lambda: ["shared"])
    source_files: list[str] = field(default_factory=list)
    identifier_notes: list[str] = field(default_factory=list)
    related: list[str] = field(default_factory=list)
    extra_start_here: list[str] = field(default_factory=list)


@dataclass
class RecipeSpec:
    key: str
    name: str
    title: str
    description: str
    summary: str
    related_skills: list[str]
    steps: list[str]
    command_examples: list[str]


def quote_yaml(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{value}"'


def display_name(name: str) -> str:
    special = {
        "ovhcloud": "OVHcloud",
        "okms": "OKMS",
        "xdsl": "XDSL",
        "ldp": "LDP",
        "iam": "IAM",
        "vps": "VPS",
        "cdn": "CDN",
        "dns": "DNS",
        "api": "API",
        "ip": "IP",
        "ssh": "SSH",
        "sql": "SQL",
    }
    words = []
    for word in name.split("-"):
        words.append(special.get(word, word.capitalize()))
    return " ".join(words)


def short_description(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > 64:
        text = text[:61].rstrip() + "..."
    if len(text) < 25:
        text = (text + " workflows").strip()
    return text


def default_prompt(name: str, summary: str) -> str:
    phrase = summary[0].lower() + summary[1:] if summary else "inspect OVHcloud resources safely."
    return f"Use ${name} to {phrase}"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n")


def parse_link_index(doc_text: str) -> list[tuple[str, str, str]]:
    matches = re.findall(r"\* \[(ovhcloud [^\]]+)\]\(([^)]+)\)\s*-\s*(.+)", doc_text)
    return [(label.strip(), file_name.strip(), desc.strip()) for label, file_name, desc in matches]


def extract_summary(doc_text: str) -> str:
    lines = [line.rstrip() for line in doc_text.splitlines()]
    seen_title = False
    for line in lines:
        if line.startswith("## "):
            seen_title = True
            continue
        if seen_title and line.strip():
            return line.strip()
    return ""


def fallback_doc_entry(source_repo: Path, doc_name: str, default_summary: str) -> tuple[str, str]:
    doc_path = source_repo / "doc" / doc_name
    if not doc_path.exists():
        return doc_name, default_summary
    return doc_name, extract_summary(doc_path.read_text()) or default_summary


def doc_command_from_path(doc_name: str) -> str:
    stem = Path(doc_name).stem
    return stem[len("ovhcloud_") :].replace("_", " ")


def classify_command(command: str) -> str:
    tokens = command.split()
    last = tokens[-1]
    if last in UNSAFE_TOKENS:
        return "unsafe"
    if last in SAFE_TOKENS:
        return "safe"
    if any(token in UNSAFE_TOKENS for token in tokens):
        return "unsafe"
    if any(token in SAFE_TOKENS for token in tokens):
        return "safe"
    return "neutral"


def select_examples(commands: list[str], kind: str, limit: int = 8) -> list[str]:
    selected = [cmd for cmd in commands if classify_command(cmd) == kind]
    return selected[:limit]


def rel_link(from_file: Path, to_file: Path) -> str:
    return Path(shutil.os.path.relpath(to_file, from_file.parent)).as_posix()


def source_doc_paths(source_repo: Path, prefix: str) -> list[Path]:
    return sorted((source_repo / "doc").glob(f"{prefix}*.md"))


def build_reference_markdown(
    spec: SkillSpec,
    repo_root: Path,
    source_repo: Path,
    commands: list[str],
    child_items: list[tuple[str, str, str]],
) -> str:
    safe_examples = select_examples(commands, "safe")
    unsafe_examples = select_examples(commands, "unsafe")
    child_lines = "\n".join(
        f"- `{label}`: {desc}" for label, _file_name, desc in child_items[:18]
    )
    safe_lines = "\n".join(f"- `{cmd}`" for cmd in safe_examples) or "- No dedicated read-only leaf verbs were detected; start with `--help` and top-level `get` or `list` commands."
    unsafe_lines = "\n".join(f"- `{cmd}`" for cmd in unsafe_examples) or "- No explicit mutating leaf verbs were detected in the generated docs for this area."
    source_lines = "\n".join(
        f"- `{path.relative_to(source_repo).as_posix()}`" for path in source_doc_paths(source_repo, spec.doc_prefix or "ovhcloud")
    )
    return f"""{GENERATED_BY}

# {spec.name} reference

## Scope

- CLI entry point: `{spec.cli_help}`
- Source docs:
{source_lines}

## Summary

{spec.summary}

## Child Command Groups

{child_lines or "- No nested command groups."}

## Read-Only Command Paths

{safe_lines}

## Documented Mutating Command Paths

Do not execute these without explicit user approval.

{unsafe_lines}
"""


def build_skill_markdown(
    spec: SkillSpec,
    bundle_dir: Path,
    skill_path: Path,
) -> str:
    prerequisites = [
        f"[ovhcloud-{item}](../{item}/SKILL.md)" if item not in {"auth", "config", "shared"} else f"[ovhcloud-{item}](../{item}/SKILL.md)"
        for item in spec.prerequisites
        if item != spec.key
    ]
    related = [f"[ovhcloud-{item}](../{item}/SKILL.md)" for item in spec.related if item != spec.key]
    reference_path = rel_link(skill_path / "SKILL.md", bundle_dir / "references" / "generated" / f"{spec.reference_slug}.md")
    prereq_lines = "\n".join(f"- {item}" for item in prerequisites) or "- This skill can be opened directly when the task is already scoped to this area."
    related_lines = "\n".join(f"- {item}" for item in related) or "- No additional area skills are required beyond shared guidance."
    when_lines = "\n".join(f"- {item}" for item in spec.when_to_use)
    start_lines = "\n".join(
        [f"- Run `{spec.cli_help}` to confirm the currently installed command tree."]
        + [f"- Read {item} first." for item in prerequisites[:1]]
        + [f"- Open the [generated command reference]({reference_path}) before choosing a verb."]
        + [f"- {item}" for item in spec.extra_start_here]
    )
    id_lines = "\n".join(f"- {item}" for item in spec.identifier_notes)
    return f"""---
name: {quote_yaml(spec.name)}
description: {quote_yaml(spec.description)}
metadata:
  category: {quote_yaml(spec.category)}
  cli_help: {quote_yaml(spec.cli_help)}
  source_ref: {quote_yaml(f"references/generated/{spec.reference_slug}.md")}
---

{GENERATED_BY}

# {spec.name}

## When To Use

{when_lines}

## Start Here

{start_lines}

## Read-Only First

- Default to `list`, `get`, `show`, `service-info`, `messages`, and other inspection verbs before anything else.
- Prefer `-o json` or `-o yaml` for scripting, and pass `--profile <name>` when more than one account context may exist.
- Treat mutating verbs in this area as documented capabilities only until the user explicitly asks for the state change.

## Important Identifiers And Flags

{id_lines}

## Prerequisites

{prereq_lines}

## Related Skills

{related_lines}

## References

- [Generated command reference]({reference_path})
"""


def build_bundle_skill(bundle_path: Path, subskills: list[SkillSpec], recipes: list[RecipeSpec]) -> str:
    subskill_lines = "\n".join(
        f"- [{spec.name}](subskills/{spec.key}/SKILL.md): {spec.summary}"
        for spec in subskills
    )
    recipe_lines = "\n".join(
        f"- [{recipe.name}](recipes/{recipe.key}/SKILL.md): {recipe.summary}"
        for recipe in recipes
    )
    return f"""---
name: "ovhcloud"
description: "OVHcloud CLI bundle: shared guidance, authentication and profiles, config resolution, Public Cloud subskills, product-family subskills, and read-only recipes for the `ovhcloud` command. Use when an agent needs to work safely with OVHcloud from the terminal."
metadata:
  category: "bundle"
  cli_help: "ovhcloud --help"
  requires_bins:
    - "ovhcloud"
  discovery_hint: "Open the bundle-local skills index first, then read the shared skill, then the task-specific subskill."
---

{GENERATED_BY}

# ovhcloud

Use this as the entrypoint for the generated OVHcloud CLI skill bundle.

## Start Here

1. Open the [skills index](references/skills-index.md) to choose the right subskill.
2. Read [ovhcloud-shared](subskills/shared/SKILL.md) for safety, authentication precedence, output formatting, filters, and help traversal.
3. Then open the subskill that matches the service family or recipe you need.

## Safety Policy

- Read-only CLI calls are allowed by default.
- Do not run create, update, delete, reboot, reinstall, reset, terminate, reply, or similar mutating verbs unless the user explicitly asks for that state change.
- During bundle validation, prefer `--help`, `list`, `get`, `show`, `service-info`, and similar inspection flows.

## Subskills

{subskill_lines}

## Recipes

{recipe_lines}

## CLI Entry Point

```bash
ovhcloud --help
```
"""


def build_shared_skill(bundle_dir: Path) -> str:
    ref = rel_link(bundle_dir / "subskills" / "shared" / "SKILL.md", bundle_dir / "references" / "generated" / "shared.md")
    return f"""---
name: "ovhcloud-shared"
description: "OVHcloud CLI shared patterns: read-only safety defaults, auth precedence, profile resolution, global flags, output formatting, gval filters, and help-driven command discovery for `ovhcloud`."
metadata:
  category: "core"
  cli_help: "ovhcloud --help"
  source_ref: "references/generated/shared.md"
---

{GENERATED_BY}

# ovhcloud-shared

## When To Use

- The task is generally about the `ovhcloud` CLI rather than one specific OVHcloud product family.
- You need safe command discovery, auth precedence, output formatting, filtering, or profile selection before touching a narrower skill.
- You need to confirm whether a workflow can stay read-only.

## Safety Defaults

- Read-only verbs such as `list`, `get`, `show`, `messages`, and `service-info` are allowed by default.
- Treat verbs such as `create`, `edit`, `delete`, `reboot`, `reinstall`, `reset`, `terminate`, `reply`, `switch`, and `set-*` as state-changing until proven otherwise.
- When uncertain, inspect the command with `--help` first rather than running it.

## Global Workflow

1. Run `ovhcloud --help` or `ovhcloud <command> --help` to map the command tree.
2. Confirm auth and profile context before the first authenticated call.
3. Prefer `-o json` or `-o yaml` for scripting and reproducible parsing.
4. Use gval output expressions or `--filter` only after you have inspected the raw fields once.

## Auth And Profiles

- Config files are resolved from `./ovh.conf`, `~/.ovh.conf`, then `/etc/ovh.conf`.
- Profile precedence is `--profile`, then `OVH_PROFILE`, then the `[default]` config entry, then legacy mode.
- Environment-based auth may use either application credentials or OAuth client credentials, depending on the account setup.

## Important Flags

- `--profile <name>` selects a profile for a single invocation.
- `-o json` and `-o yaml` are the safest automation outputs.
- `-o '<expr>'` and `--filter '<expr>'` use gval expressions; inspect fields before relying on them.
- `--debug` is useful for troubleshooting but may expose sensitive request details in logs.

## References

- [Generated shared reference]({ref})
- [ovhcloud-auth](../auth/SKILL.md)
- [ovhcloud-config](../config/SKILL.md)
"""


def build_auth_skill(bundle_dir: Path) -> str:
    ref = rel_link(bundle_dir / "subskills" / "auth" / "SKILL.md", bundle_dir / "references" / "generated" / "auth.md")
    return f"""---
name: "ovhcloud-auth"
description: "OVHcloud CLI auth: explain `ovhcloud login`, config-file and env-var credentials, profile-aware auth resolution, and safe authenticated smoke checks without mutating resources."
metadata:
  category: "core"
  cli_help: "ovhcloud login --help"
  source_ref: "references/generated/auth.md"
---

{GENERATED_BY}

# ovhcloud-auth

## When To Use

- You need to explain how `ovhcloud` authenticates or which credentials source wins.
- You need to use `ovhcloud login`, environment variables, or `.ovh.conf` safely.
- You want a minimal authenticated read-only smoke test before opening a service-specific skill.

## Start Here

- Read [ovhcloud-shared](../shared/SKILL.md) first.
- Open the [generated auth reference]({ref}) for the exact config keys and precedence rules.
- Prefer a read-only smoke test such as `ovhcloud account get -o json` after auth is confirmed.

## Read-Only First

- Explaining or inspecting authentication is safe.
- `ovhcloud login` itself changes local credentials but does not mutate OVHcloud resources; still confirm before using it in a shared machine context.
- Avoid mutating service commands while validating credentials; use `account get`, `cloud project list`, or another read-only command instead.

## Important Identifiers And Flags

- Application-key auth uses `OVH_APPLICATION_KEY`, `OVH_APPLICATION_SECRET`, and `OVH_CONSUMER_KEY`.
- OAuth client auth uses `OVH_CLIENT_ID` and `OVH_CLIENT_SECRET`.
- `OVH_ENDPOINT` selects the API endpoint, and `--profile` or `OVH_PROFILE` selects the named profile.

## References

- [Generated auth reference]({ref})
- [ovhcloud-config](../config/SKILL.md)
"""


def build_config_skill(bundle_dir: Path) -> str:
    ref = rel_link(bundle_dir / "subskills" / "config" / "SKILL.md", bundle_dir / "references" / "generated" / "config.md")
    return f"""---
name: "ovhcloud-config"
description: "OVHcloud CLI config: inspect config values, endpoints, and profiles; explain `ovhcloud config ...`; and keep multi-account workflows predictable."
metadata:
  category: "core"
  cli_help: "ovhcloud config --help"
  source_ref: "references/generated/config.md"
---

{GENERATED_BY}

# ovhcloud-config

## When To Use

- The task is about `ovhcloud config ...`, profile management, endpoint selection, or default project resolution.
- You need to inspect the active profile or explain how configuration is resolved from file and environment.
- You need to document a config-changing command without actually applying it yet.

## Start Here

- Read [ovhcloud-shared](../shared/SKILL.md) first.
- Open the [generated config reference]({ref}) for the `config profile`, `config set`, and `config show` subcommands.
- Prefer `ovhcloud config show` and `ovhcloud config profile show` before any config-changing verb.

## Read-Only First

- `ovhcloud config show` and `ovhcloud config profile show` are the safest inspection entry points.
- `config set`, `config set-endpoint`, `config profile switch`, and `config profile delete` change local state and require explicit user approval.
- When documenting multi-profile flows, keep examples generic and do not overwrite the active profile during validation.

## Important Identifiers And Flags

- Profiles are stored as `[profile:<name>]` blocks in `~/.ovh.conf`.
- The active profile can come from `--profile`, `OVH_PROFILE`, or the `[default]` config section.
- `default_cloud_project` is profile-scoped, so account context matters when interpreting Public Cloud commands.

## References

- [Generated config reference]({ref})
- [ovhcloud-auth](../auth/SKILL.md)
"""


def build_recipe_markdown(bundle_dir: Path, recipe: RecipeSpec) -> str:
    related_lines = "\n".join(
        f"- [ovhcloud-{item}](../../subskills/{item}/SKILL.md)" for item in recipe.related_skills
    )
    step_lines = "\n".join(f"{index}. {step}" for index, step in enumerate(recipe.steps, start=1))
    example_lines = "\n".join(f"- `{cmd}`" for cmd in recipe.command_examples)
    return f"""---
name: {quote_yaml(recipe.name)}
description: {quote_yaml(recipe.description)}
metadata:
  category: "recipe"
---

{GENERATED_BY}

# {recipe.name}

## Goal

{recipe.summary}

## Related Skills

{related_lines}

## Workflow

{step_lines}

## Command Skeletons

{example_lines}

## Safety

- Keep the workflow read-only unless the user explicitly requests a state change.
- If a later step would require a mutating verb, stop and confirm that separately instead of continuing by default.
"""


def build_skills_index(subskills: list[SkillSpec], recipes: list[RecipeSpec]) -> str:
    groups = {
        "Core": [spec for spec in subskills if spec.category == "core"],
        "Public Cloud": [spec for spec in subskills if spec.category == "public-cloud"],
        "Product Families": [spec for spec in subskills if spec.category == "product-family"],
    }
    parts = [GENERATED_BY, "", "# Skills Index", "", "Generated skill docs for the installable `ovhcloud` bundle.", "## Bundle", "", "Skill Description", "- [ovhcloud](../skills/ovhcloud/SKILL.md) OVHcloud CLI bundle: shared guidance, auth, config resolution, Public Cloud subskills, product-family subskills, and read-only recipes for the `ovhcloud` command."]
    for heading, items in groups.items():
        parts.extend(["", f"## {heading}", "", "Skill Description"])
        for spec in items:
            parts.append(f"- [{spec.name}](../skills/ovhcloud/subskills/{spec.key}/SKILL.md) {spec.summary}")
    parts.extend(["", "## Recipes", "", "Skill Description"])
    for recipe in recipes:
        parts.append(f"- [{recipe.name}](../skills/ovhcloud/recipes/{recipe.key}/SKILL.md) {recipe.summary}")
    return "\n".join(parts) + "\n"


def build_local_skills_index(subskills: list[SkillSpec], recipes: list[RecipeSpec]) -> str:
    groups = {
        "Core": [spec for spec in subskills if spec.category == "core"],
        "Public Cloud": [spec for spec in subskills if spec.category == "public-cloud"],
        "Product Families": [spec for spec in subskills if spec.category == "product-family"],
    }
    parts = [GENERATED_BY, "", "# Skills Index", "", "Generated skill docs for the installable `ovhcloud` bundle.", "## Bundle", "", "Skill Description", "- [ovhcloud](../SKILL.md) OVHcloud CLI bundle: shared guidance, auth, config resolution, Public Cloud subskills, product-family subskills, and read-only recipes for the `ovhcloud` command."]
    for heading, items in groups.items():
        parts.extend(["", f"## {heading}", "", "Skill Description"])
        for spec in items:
            parts.append(f"- [{spec.name}](../subskills/{spec.key}/SKILL.md) {spec.summary}")
    parts.extend(["", "## Recipes", "", "Skill Description"])
    for recipe in recipes:
        parts.append(f"- [{recipe.name}](../recipes/{recipe.key}/SKILL.md) {recipe.summary}")
    return "\n".join(parts) + "\n"


def build_recipe_index(recipes: list[RecipeSpec]) -> str:
    parts = [GENERATED_BY, "", "# Recipes Index", "", "Read-only workflow recipes built on top of the OVHcloud CLI bundle.", "", "Skill Description"]
    for recipe in recipes:
        parts.append(f"- [{recipe.name}](./{recipe.key}/SKILL.md) {recipe.summary}")
    return "\n".join(parts) + "\n"


def build_core_references(source_repo: Path) -> dict[str, str]:
    shared_text = (source_repo / "doc" / "ovhcloud.md").read_text()
    auth_text = (source_repo / "doc" / "authentication.md").read_text()
    profiles_text = (source_repo / "doc" / "profiles.md").read_text()
    config_text = (source_repo / "doc" / "ovhcloud_config.md").read_text()
    return {
        "shared": f"""{GENERATED_BY}

# ovhcloud-shared reference

## Source Docs

- `doc/ovhcloud.md`
- `doc/authentication.md`
- `doc/profiles.md`

## CLI Basics

{extract_summary(shared_text)}

## Global Discovery Tips

- Start with `ovhcloud --help`, then drill into `ovhcloud <command> --help`.
- Prefer `-o json` or `-o yaml` for structured output.
- Use `--filter '<expr>'` and `-o '<expr>'` only after inspecting the returned fields.

## Auth Precedence

- Config files resolve from `./ovh.conf`, `~/.ovh.conf`, and `/etc/ovh.conf`.
- Profile selection precedence is `--profile`, then `OVH_PROFILE`, then the config default profile, then legacy mode.
- Auth credentials may come from application keys or OAuth client credentials.

## Source Highlights

{extract_summary(auth_text)}

{extract_summary(profiles_text)}
""",
        "auth": f"""{GENERATED_BY}

# ovhcloud-auth reference

## Source Docs

- `doc/authentication.md`
- `doc/profiles.md`
- `doc/ovhcloud_login.md`

## Supported Auth Modes

{extract_summary(auth_text)}

## Profile Notes

{extract_summary(profiles_text)}

## Safe Smoke Tests

- `ovhcloud version`
- `ovhcloud account get -o json`
- `ovhcloud cloud project list -o json`
""",
        "config": f"""{GENERATED_BY}

# ovhcloud-config reference

## Source Docs

- `doc/ovhcloud_config.md`
- `doc/profiles.md`
- `doc/ovhcloud_config_profile.md`
- `doc/ovhcloud_config_show.md`
- `doc/ovhcloud_config_set.md`
- `doc/ovhcloud_config_set-endpoint.md`

## Summary

{extract_summary(config_text)}

## Read-Only Entry Points

- `ovhcloud config show`
- `ovhcloud config profile list`
- `ovhcloud config profile show`

## Config-Changing Verbs

Documented but user-approved only:

- `ovhcloud config set`
- `ovhcloud config set-endpoint`
- `ovhcloud config profile switch`
- `ovhcloud config profile delete`
""",
    }


def build_recipe_specs() -> list[RecipeSpec]:
    return [
        RecipeSpec(
            key="inventory-account",
            name="recipe-inventory-account",
            title="Inventory Account",
            description="Inventory an OVHcloud account or Public Cloud estate with read-only `ovhcloud` commands.",
            summary="Inventory an account, projects, and core services with read-only `ovhcloud` commands.",
            related_skills=["shared", "account", "cloud-project", "vps", "baremetal", "webhosting"],
            steps=[
                "Confirm the active profile and auth context with `ovhcloud account get -o json`.",
                "List account-wide service families such as VPS, bare metal, webhosting, and cloud projects.",
                "Capture identifiers from the read-only responses before drilling into one service family.",
            ],
            command_examples=[
                "ovhcloud account get -o json",
                "ovhcloud cloud project list -o json",
                "ovhcloud vps list -o json",
                "ovhcloud baremetal list -o json",
                "ovhcloud webhosting list -o json",
            ],
        ),
        RecipeSpec(
            key="audit-iam",
            name="recipe-audit-iam",
            title="Audit IAM",
            description="Audit OVHcloud IAM users, policies, permissions groups, resources, and resource groups without changing access state.",
            summary="Review IAM objects and permissions without mutating access state.",
            related_skills=["shared", "iam"],
            steps=[
                "List IAM users, policies, permissions groups, resources, and resource groups.",
                "Fetch individual records only after the list output reveals the exact identifiers you need.",
                "Summarize effective access and stop before any create, update, or delete verb.",
            ],
            command_examples=[
                "ovhcloud iam user list -o json",
                "ovhcloud iam policy list -o json",
                "ovhcloud iam permissions-group list -o json",
                "ovhcloud iam resource list -o json",
                "ovhcloud iam resource-group list -o json",
            ],
        ),
        RecipeSpec(
            key="inspect-compute",
            name="recipe-inspect-compute",
            title="Inspect Compute",
            description="Inspect VPS, bare metal, and Public Cloud compute resources with read-only OVHcloud CLI commands.",
            summary="Inspect compute fleets across VPS, bare metal, and Public Cloud instances.",
            related_skills=["shared", "vps", "baremetal", "cloud-instance"],
            steps=[
                "List the compute resources in the relevant family first.",
                "Fetch detailed records only for the resources you need to examine more closely.",
                "Use task, backup, snapshot, and options commands to understand operational state without changing it.",
            ],
            command_examples=[
                "ovhcloud vps list -o json",
                "ovhcloud baremetal list -o json",
                "ovhcloud cloud instance list --cloud-project <project_id> -o json",
                "ovhcloud vps list-tasks <service_name> -o json",
                "ovhcloud cloud instance snapshot list --cloud-project <project_id> <instance_id> -o json",
            ],
        ),
        RecipeSpec(
            key="inspect-kubeconfig",
            name="recipe-inspect-kubeconfig",
            title="Inspect Kubeconfig",
            description="Generate kubeconfig for cluster inspection only, without changing cluster state.",
            summary="Generate kubeconfig locally so cluster inspection can continue outside the CLI.",
            related_skills=["shared", "cloud-kube"],
            steps=[
                "List clusters and fetch the target cluster record first.",
                "Generate kubeconfig only after the cluster identifier is confirmed.",
                "Treat kubeconfig generation as a local-file step, then continue inspection with `kubectl` outside this bundle if needed.",
            ],
            command_examples=[
                "ovhcloud cloud kube list --cloud-project <project_id> -o json",
                "ovhcloud cloud kube get --cloud-project <project_id> <cluster_id> -o json",
                "ovhcloud cloud kube kubeconfig generate --cloud-project <project_id> <cluster_id>",
            ],
        ),
        RecipeSpec(
            key="audit-dns",
            name="recipe-audit-dns",
            title="Audit DNS",
            description="Inspect domains, zones, and records safely with OVHcloud CLI DNS commands.",
            summary="Review domains, DNS zones, and records without refreshing or editing them.",
            related_skills=["shared", "domain-name", "domain-zone"],
            steps=[
                "List zones or domain names first, then fetch the specific zone you need.",
                "List records for the zone and capture IDs before any deeper analysis.",
                "Stop before `refresh`, `create`, `edit`, or `delete` operations unless the user later approves them.",
            ],
            command_examples=[
                "ovhcloud domain-zone list -o json",
                "ovhcloud domain-zone get <zone_name> -o json",
                "ovhcloud domain-zone record list <zone_name> -o json",
                "ovhcloud domain-name list -o json",
            ],
        ),
        RecipeSpec(
            key="inspect-storage",
            name="recipe-inspect-storage",
            title="Inspect Storage",
            description="Inspect object, block, and file storage resources in OVHcloud without creating or deleting data.",
            summary="Inspect object, block, and file storage resources with read-only calls.",
            related_skills=["shared", "cloud-storage", "storage-netapp", "dedicated-ceph"],
            steps=[
                "List the relevant storage services in the target project or product family.",
                "Use object, credential, backup, lifecycle, and share inspection verbs to understand current state.",
                "Do not execute bulk-delete, restore, edit, or create verbs unless the user explicitly requests them.",
            ],
            command_examples=[
                "ovhcloud cloud storage s3 list --cloud-project <project_id> -o json",
                "ovhcloud cloud storage block list --cloud-project <project_id> -o json",
                "ovhcloud cloud storage file share list --cloud-project <project_id> -o json",
                "ovhcloud dedicated-ceph list -o json",
                "ovhcloud storage-netapp list -o json",
            ],
        ),
        RecipeSpec(
            key="inspect-webhosting",
            name="recipe-inspect-webhosting",
            title="Inspect Webhosting",
            description="Inspect OVHcloud webhosting services, databases, runtimes, tasks, and deployments with read-only commands.",
            summary="Inspect webhosting state, databases, runtimes, incidents, and tasks safely.",
            related_skills=["shared", "webhosting", "hosting-private-database"],
            steps=[
                "List webhosting services and fetch the specific service record you care about.",
                "Inspect attached databases, runtimes, websites, incidents, and tasks through read-only verbs.",
                "Document mutating operations such as `edit`, `terminate`, or `restore-snapshot` separately without executing them.",
            ],
            command_examples=[
                "ovhcloud webhosting list -o json",
                "ovhcloud webhosting get <service_name> -o json",
                "ovhcloud webhosting db list <service_name> -o json",
                "ovhcloud webhosting runtime get <service_name> <runtime_id> -o json",
                "ovhcloud webhosting tasks list <service_name> -o json",
            ],
        ),
        RecipeSpec(
            key="trace-support",
            name="recipe-trace-support",
            title="Trace Support",
            description="Trace OVHcloud support tickets and ticket messages without replying or changing ticket state.",
            summary="List tickets and inspect messages without replying to support.",
            related_skills=["shared", "support-tickets"],
            steps=[
                "List tickets first to capture the identifiers and current status.",
                "Fetch the ticket and its messages to reconstruct the timeline.",
                "Stop before `reply` unless the user explicitly wants to send a response.",
            ],
            command_examples=[
                "ovhcloud support-tickets list -o json",
                "ovhcloud support-tickets get <ticket_id> -o json",
                "ovhcloud support-tickets messages <ticket_id> -o json",
            ],
        ),
        RecipeSpec(
            key="review-network-topology",
            name="recipe-review-network-topology",
            title="Review Network Topology",
            description="Review floating IPs, failover IPs, vRack, and load balancers with read-only OVHcloud commands.",
            summary="Review network topology across Public Cloud IPs, load balancers, and vRack services.",
            related_skills=["shared", "ip", "vrack", "vrackservices", "cloud-floating-ip", "cloud-ip-failover", "cloud-loadbalancer"],
            steps=[
                "Start from the broad network inventory: IP resources, vRack resources, and load balancers.",
                "Drill into listeners, pools, health monitors, or failover records only after you identify the exact resource.",
                "Avoid `attach`, `associate`, `create`, `edit`, and `delete` verbs unless the user later requests a topology change.",
            ],
            command_examples=[
                "ovhcloud ip list -o json",
                "ovhcloud vrack list -o json",
                "ovhcloud vrackservices list -o json",
                "ovhcloud cloud floating-ip list --cloud-project <project_id> -o json",
                "ovhcloud cloud ip-failover list --cloud-project <project_id> -o json",
                "ovhcloud cloud loadbalancer list --cloud-project <project_id> -o json",
            ],
        ),
    ]


def build_skill_specs(source_repo: Path) -> list[SkillSpec]:
    top_index = parse_link_index((source_repo / "doc" / "ovhcloud.md").read_text())
    cloud_index = parse_link_index((source_repo / "doc" / "ovhcloud_cloud.md").read_text())
    top_map = {label.replace("ovhcloud ", ""): (file_name, desc) for label, file_name, desc in top_index}
    cloud_map = {label.replace("ovhcloud cloud ", ""): (file_name, desc) for label, file_name, desc in cloud_index}

    specs: list[SkillSpec] = [
        SkillSpec(
            key="shared",
            name="ovhcloud-shared",
            title="Shared",
            category="core",
            cli_help="ovhcloud --help",
            description="OVHcloud CLI shared patterns: read-only safety defaults, auth precedence, profile resolution, global flags, output formatting, gval filters, and help-driven command discovery for `ovhcloud`.",
            summary="OVHcloud CLI shared patterns: safety defaults, auth precedence, profiles, global flags, filtering, and help traversal.",
            discovery_hint="Start here for safety policy, profile selection, and global CLI behavior before using service-specific skills.",
            when_to_use=[
                "The task is generally about the `ovhcloud` CLI rather than one specific product family.",
                "You need safety guidance, auth precedence, or help-driven command discovery before choosing a service-specific skill.",
            ],
            reference_slug="shared",
            doc_prefix="ovhcloud",
            prerequisites=[],
            source_files=["doc/ovhcloud.md", "doc/authentication.md", "doc/profiles.md"],
            identifier_notes=[
                "Global output flags include `-o json`, `-o yaml`, and gval expressions such as `-o 'id'`.",
                "`--profile <name>` overrides the active profile for a single invocation.",
                "`--debug` is useful for troubleshooting but may expose sensitive request metadata in logs.",
            ],
            related=["auth", "config"],
        ),
        SkillSpec(
            key="auth",
            name="ovhcloud-auth",
            title="Auth",
            category="core",
            cli_help="ovhcloud login --help",
            description="OVHcloud CLI auth: explain `ovhcloud login`, config-file and env-var credentials, profile-aware auth resolution, and safe authenticated smoke checks without mutating resources.",
            summary="OVHcloud CLI auth: `ovhcloud login`, env vars, config files, and profile-aware auth resolution.",
            discovery_hint="Use this for credential precedence, login flows, and safe authenticated smoke tests.",
            when_to_use=[
                "You need to explain or validate how `ovhcloud` authenticates before running service commands.",
                "You need to work with `ovhcloud login`, environment variables, or `.ovh.conf` auth sections.",
            ],
            reference_slug="auth",
            doc_prefix="ovhcloud_login",
            prerequisites=["shared"],
            source_files=["doc/authentication.md", "doc/profiles.md", "doc/ovhcloud_login.md"],
            identifier_notes=[
                "Application-key auth uses `OVH_APPLICATION_KEY`, `OVH_APPLICATION_SECRET`, and `OVH_CONSUMER_KEY`.",
                "OAuth client auth uses `OVH_CLIENT_ID` and `OVH_CLIENT_SECRET`.",
                "`OVH_ENDPOINT` and `--profile` both affect which credentials set is resolved.",
            ],
            related=["config"],
        ),
        SkillSpec(
            key="config",
            name="ovhcloud-config",
            title="Config",
            category="core",
            cli_help="ovhcloud config --help",
            description="OVHcloud CLI config: inspect config values, endpoints, and profiles; explain `ovhcloud config ...`; and keep multi-account workflows predictable.",
            summary="OVHcloud CLI config: inspect config values, endpoints, and profile-aware defaults safely.",
            discovery_hint="Use this when the task is about profile management, config inspection, or local endpoint defaults.",
            when_to_use=[
                "The task is about `ovhcloud config`, profiles, endpoint selection, or default cloud project resolution.",
                "You need to inspect local config without mutating it yet.",
            ],
            reference_slug="config",
            doc_prefix="ovhcloud_config",
            prerequisites=["shared"],
            source_files=["doc/ovhcloud_config.md", "doc/profiles.md"],
            identifier_notes=[
                "`ovhcloud config show` and `ovhcloud config profile show` are the safest inspection entry points.",
                "`default_cloud_project` is profile-scoped and affects Public Cloud commands.",
                "`config set`, `config set-endpoint`, and profile switching change local state and require explicit approval.",
            ],
            related=["auth"],
        ),
    ]

    for command in TOP_LEVEL_ORDER:
        if command in EXCLUDED_TOP_LEVEL:
            continue
        file_name, desc = top_map.get(command, fallback_doc_entry(source_repo, f"ovhcloud_{command}.md", f"Manage {command} resources"))
        skill_key = command
        skill_name = f"ovhcloud-{command}"
        summary = f"OVHcloud CLI {command}: {desc}"
        cli_help = f"ovhcloud {command} --help"
        specs.append(
            SkillSpec(
                key=skill_key,
                name=skill_name,
                title=display_name(command),
                category="product-family",
                cli_help=cli_help,
                description=f"{summary} Use when the task centers on `ovhcloud {command} ...`; start with read-only inspection and treat mutating verbs as documented-only unless the user explicitly approves them.",
                summary=summary,
                discovery_hint=f"Use `{cli_help}` first, then inspect the generated command reference before choosing a verb.",
                when_to_use=[
                    f"The task is specifically about the `{command}` product family in OVHcloud.",
                    "You need read-only discovery first and a concise map of the documented mutating verbs before acting.",
                ],
                reference_slug=skill_key,
                doc_prefix=Path(file_name).stem,
                identifier_notes=[
                    "Start with `list` or `get` commands to discover the service identifiers used by deeper verbs.",
                    "Prefer `-o json` or `-o yaml` when passing results into later analysis or summaries.",
                ],
                related=["shared"] + (["auth"] if command in {"account", "iam"} else []),
            )
        )

    for command in CLOUD_ORDER:
        file_name, desc = cloud_map.get(command, fallback_doc_entry(source_repo, f"ovhcloud_cloud_{command}.md", f"Manage cloud {command} resources"))
        skill_key = f"cloud-{command}"
        skill_name = f"ovhcloud-cloud-{command}"
        cli_help = f"ovhcloud cloud {command} --help"
        notes = [
            "Most commands in this area require `--cloud-project <project_id>` unless a default cloud project is already configured.",
            "Start with `list` or `get` commands to capture resource IDs before using deeper nested verbs.",
        ]
        if command in {"instance", "kube", "loadbalancer", "storage", "container-registry", "managed-database", "managed-analytics", "network", "floating-ip", "ip-failover"}:
            notes.append("Capture the project ID explicitly in notes and examples even if your local config has a default project.")
        specs.append(
            SkillSpec(
                key=skill_key,
                name=skill_name,
                title=f"Cloud {display_name(command)}",
                category="public-cloud",
                cli_help=cli_help,
                description=f"OVHcloud Public Cloud `{command}`: {desc} Use when the task centers on `ovhcloud cloud {command} ...`; stay read-only by default and document mutating verbs separately.",
                summary=f"OVHcloud Public Cloud `{command}`: {desc}",
                discovery_hint=f"Use `{cli_help}` first, then inspect the generated command reference and confirm the target cloud project.",
                when_to_use=[
                    f"The task is specifically about Public Cloud `{command}` resources.",
                    "You need a focused map of the nested command groups without wading through the entire `ovhcloud cloud` surface.",
                ],
                reference_slug=skill_key,
                doc_prefix=Path(file_name).stem,
                identifier_notes=notes,
                related=["shared", "config", "cloud-project"],
            )
        )

    return specs


def build_generated_content(repo_root: Path, source_repo: Path) -> None:
    bundle_dir = repo_root / "skills" / "ovhcloud"
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    (repo_root / "docs").mkdir(parents=True, exist_ok=True)
    (repo_root / "skills").mkdir(parents=True, exist_ok=True)

    skill_specs = build_skill_specs(source_repo)
    recipe_specs = build_recipe_specs()

    bundle_subskills = skill_specs
    top_doc_links = parse_link_index((source_repo / "doc" / "ovhcloud.md").read_text())
    cloud_doc_links = parse_link_index((source_repo / "doc" / "ovhcloud_cloud.md").read_text())
    link_lookup = {Path(file_name).stem: parse_link_index((source_repo / "doc" / file_name).read_text()) for _, file_name, _ in top_doc_links + cloud_doc_links}

    core_refs = build_core_references(source_repo)
    for name, content in core_refs.items():
        write(bundle_dir / "references" / "generated" / f"{name}.md", content)

    for spec in skill_specs:
        if spec.key == "shared":
            skill_md = build_shared_skill(bundle_dir)
            skill_dir = bundle_dir / "subskills" / spec.key
        elif spec.key == "auth":
            skill_md = build_auth_skill(bundle_dir)
            skill_dir = bundle_dir / "subskills" / spec.key
        elif spec.key == "config":
            skill_md = build_config_skill(bundle_dir)
            skill_dir = bundle_dir / "subskills" / spec.key
        else:
            skill_dir = bundle_dir / "subskills" / spec.key
            skill_md = build_skill_markdown(spec, bundle_dir, skill_dir)
            doc_prefix = spec.doc_prefix or "ovhcloud"
            child_items = link_lookup.get(doc_prefix, [])
            commands = [doc_command_from_path(path.name) for path in source_doc_paths(source_repo, doc_prefix)]
            write(
                bundle_dir / "references" / "generated" / f"{spec.reference_slug}.md",
                build_reference_markdown(spec, repo_root, source_repo, commands, child_items),
            )
        write(skill_dir / "SKILL.md", skill_md)
        write(skill_dir / "agents" / "openai.yaml", "\n".join([
            "interface:",
            f"  display_name: {quote_yaml(display_name(spec.name))}",
            f"  short_description: {quote_yaml(short_description(spec.summary))}",
            f"  brand_color: {quote_yaml(OVH_BRAND_COLOR)}",
            f"  default_prompt: {quote_yaml(default_prompt(spec.name, spec.summary))}",
        ]))

    for recipe in recipe_specs:
        recipe_dir = bundle_dir / "recipes" / recipe.key
        write(recipe_dir / "SKILL.md", build_recipe_markdown(bundle_dir, recipe))
        write(recipe_dir / "agents" / "openai.yaml", "\n".join([
            "interface:",
            f"  display_name: {quote_yaml(display_name(recipe.name))}",
            f"  short_description: {quote_yaml(short_description(recipe.summary))}",
            f"  brand_color: {quote_yaml(OVH_BRAND_COLOR)}",
            f"  default_prompt: {quote_yaml(default_prompt(recipe.name, recipe.summary))}",
        ]))

    bundle_skill = build_bundle_skill(bundle_dir, bundle_subskills, recipe_specs)
    write(bundle_dir / "SKILL.md", bundle_skill)
    write(bundle_dir / "agents" / "openai.yaml", "\n".join([
        "interface:",
        f"  display_name: {quote_yaml('OVHcloud')}",
        f"  short_description: {quote_yaml('OVHcloud CLI bundle and workflows')}",
        f"  brand_color: {quote_yaml(OVH_BRAND_COLOR)}",
        f"  default_prompt: {quote_yaml('Use $ovhcloud to choose the right OVHcloud CLI subskill and stay read-only by default.')}",
    ]))

    write(bundle_dir / "references" / "skills-index.md", build_local_skills_index(skill_specs, recipe_specs))
    write(bundle_dir / "recipes" / "index.md", build_recipe_index(recipe_specs))
    write(repo_root / "docs" / "skills.md", build_skills_index(skill_specs, recipe_specs))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the OVHcloud skill bundle from an ovhcloud-cli clone.")
    parser.add_argument(
        "--source-repo",
        default="../ovhcloud-cli",
        help="Path to the source ovhcloud-cli repository clone.",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to the skill bundle repository root.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    source_repo = Path(args.source_repo).resolve()
    if not (source_repo / "doc" / "ovhcloud.md").exists():
        raise SystemExit(f"Could not find source docs under {source_repo}")
    build_generated_content(repo_root, source_repo)
    print(f"Generated OVHcloud skill bundle under {repo_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
